# Generated by Django 5.1.2 on 2024-12-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
