# Generated by Django 5.1.4 on 2025-02-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', to_field='unique_id'),
        ),
    ]
