# Generated by Django 5.1.4 on 2025-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='availability',
            field=models.JSONField(default=dict),
        ),
    ]
