# Generated by Django 5.1.4 on 2025-01-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_artisanprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='service_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
