# Generated by Django 5.1.4 on 2025-02-20 14:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_artisanprofile_previous_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='previous_jobs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='previous_jobs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'pdf', 'jpg', 'jpeg'])]), blank=True, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='qualifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='qualifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'pdf', 'jpg', 'jpeg'])]), blank=True, null=True, size=5),
        ),
    ]
