# Generated by Django 5.1.4 on 2025-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_artisanprofile_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='business_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
