# Generated by Django 5.1.4 on 2025-01-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_artisanprofile_service_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
