# Generated by Django 5.1.4 on 2025-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_artisanprofile_previous_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
