# Generated by Django 5.1.4 on 2025-01-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_artisanprofile_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='service_cost',
        ),
    ]
