# Generated by Django 5.1.4 on 2025-02-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_artisanprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='identification_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
