# Generated by Django 5.1.4 on 2025-02-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_artisanprofile_identification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='business_location',
        ),
    ]
