# Generated by Django 5.1.4 on 2025-02-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_artisanprofile_business_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisanprofile',
            old_name='is_approved',
            new_name='is_suspended',
        ),
    ]
