# Generated by Django 5.1.4 on 2025-02-21 22:16

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_is_approved_artisanprofile_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='userImages/', validators=[profiles.models.validate_file_extension]),
        ),
    ]
