# Generated by Django 5.1.4 on 2025-02-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_artisanprofile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
