# Generated by Django 5.1.4 on 2025-02-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_artisanprofile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='identification_code',
        ),
    ]
