# Generated by Django 5.1.4 on 2025-02-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='NIN_doc',
            field=models.ImageField(blank=True, null=True, upload_to='artisan_files/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_doc',
            field=models.ImageField(blank=True, null=True, upload_to='artisan_files/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='proof_of_address',
            field=models.ImageField(blank=True, null=True, upload_to='artisan_files/'),
        ),
    ]
