# Generated by Django 5.1.4 on 2025-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_about_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Lagos, Nigeria', max_length=255),
        ),
    ]
