# Generated by Django 5.1.4 on 2025-02-20 14:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_address_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='NIN_doc',
            field=models.FileField(blank=True, null=True, upload_to='artisan_files/', validators=[users.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='other_doc',
            field=models.FileField(blank=True, null=True, upload_to='artisan_files/', validators=[users.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='artisan_files/', validators=[users.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='userImages/', validators=[users.models.validate_file_extension]),
        ),
    ]
