# Generated by Django 5.1.4 on 2025-02-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_nin_doc_alter_customuser_other_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
