# Generated by Django 5.1.4 on 2025-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_is_subscribed_customuser_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identification_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
