# Generated by Django 5.1.4 on 2025-02-19 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_customuser_address_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('postName', models.CharField(blank=True, max_length=255, null=True)),
                ('simpleDescription', models.TextField(blank=True, null=True)),
                ('complexDescription', models.TextField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('num_appllications', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=50)),
                ('issue_type', models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complex')], default='simple', max_length=50)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='job_attachments/')),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='users.customuser', to_field='unique_id')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='users.customuser', to_field='unique_id')),
                ('service_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='jobs.servicecategory', to_field='unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_reviews', to='users.customuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='users.customuser')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrequest')),
            ],
        ),
    ]
