# Generated by Django 5.1.4 on 2025-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='num_appllications',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
