# Generated by Django 5.1.4 on 2025-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='job_attachments/'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complex')], default='simple', max_length=50),
        ),
    ]
