# Generated by Django 5.1.4 on 2025-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='admin_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='artisan_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='customer_done',
            field=models.BooleanField(default=False),
        ),
    ]
