# Generated by Django 5.1.4 on 2025-01-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobrequest_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='job_type',
            new_name='issue_type',
        ),
    ]
