# Generated by Django 5.1.4 on 2025-02-28 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_jobrequest_admin_done_jobrequest_artisan_done_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notofication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('job_completed', 'Job Completed'), ('payment_made', 'Payment Made'), ('subscription_created', 'Subscription Created')], max_length=50)),
                ('artisan', models.ForeignKey(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', to_field='unique_id')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='users.customuser', to_field='unique_id')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrequest', to_field='unique_id')),
            ],
        ),
    ]
