# Generated by Django 5.1.2 on 2024-12-09 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reliability_rating', models.IntegerField(blank=True, null=True)),
                ('workmanship_rating', models.IntegerField(blank=True, null=True)),
                ('tidiness_rating', models.IntegerField(blank=True, null=True)),
                ('courtesy_rating', models.IntegerField(blank=True, null=True)),
                ('overall_rating', models.IntegerField()),
                ('review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('value_of_work', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_reviews', to=settings.AUTH_USER_MODEL)),
                ('service_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrequest')),
            ],
        ),
    ]
