# Generated by Django 5.1.2 on 2024-12-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('tradeReviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradereview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_reviews', to=settings.AUTH_USER_MODEL, to_field='unique_id'),
        ),
        migrations.AlterField(
            model_name='tradereview',
            name='service_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.servicecategory', to_field='unique_id'),
        ),
    ]
