# Generated by Django 5.1.2 on 2024-12-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeReviews', '0002_alter_tradereview_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradereview',
            name='overall_rating',
        ),
    ]
