# Generated by Django 5.1.2 on 2024-12-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('tradeReviews', '0004_alter_tradereview_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradereview',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.servicecategory', to_field='unique_id'),
        ),
    ]
