# Generated by Django 5.1.4 on 2025-02-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, default='Unknown Bank', max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, default='0000000000', max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, default='Unknown Name', max_length=255, null=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=7)),
            ],
        ),
    ]
