# Generated by Django 5.1.4 on 2025-02-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
        ('users', '0006_customuser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='artisan',
            field=models.OneToOneField(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', to_field='unique_id'),
        ),
    ]
