# Generated by Django 5.1.4 on 2025-02-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_alter_payouts_artisan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='account_name',
            field=models.CharField(blank=True, default='Unknown Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='account_number',
            field=models.CharField(blank=True, default='0000000000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=7),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='bank_name',
            field=models.CharField(blank=True, default='Unknown Bank', max_length=255, null=True),
        ),
    ]
