# Generated by Django 5.1.4 on 2025-02-05 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('reliability_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('workmanship_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('tidiness_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('courtesy_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('value_of_work', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_experience', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_review_set', to='users.customuser', to_field='unique_id')),
                ('reviewer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_review_written_set', to='users.customuser', to_field='unique_id')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_service_reviews', to='jobs.servicecategory', to_field='unique_id')),
            ],
        ),
    ]
