# Generated by Django 5.1.4 on 2025-02-26 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisanReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanreview',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
