# Generated by Django 5.1.2 on 2024-12-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisanReview', '0002_artisanreview_reviewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanreview',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='courtesy_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='date_of_experience',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='reliability_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='review_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='service_category_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='tidiness_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='value_of_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='workmanship_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisanreview',
            name='artisan_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
