# Generated by Django 5.1.2 on 2024-12-28 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisanReview', '0003_artisanreview_contact_email_and_more'),
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanreview',
            name='artisan_name',
        ),
        migrations.RemoveField(
            model_name='artisanreview',
            name='service_category_id',
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_service_reviews', to='jobs.servicecategory', to_field='unique_id'),
        ),
        migrations.AlterField(
            model_name='artisanreview',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_review_set', to=settings.AUTH_USER_MODEL, to_field='unique_id'),
        ),
        migrations.AlterField(
            model_name='artisanreview',
            name='reviewer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_review_written_set', to=settings.AUTH_USER_MODEL, to_field='unique_id'),
        ),
    ]
