# Generated by Django 5.1.4 on 2025-02-19 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0003_alter_customuser_address_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freelancer_service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_duration', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artisan', models.ForeignKey(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', to_field='unique_id')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrequest', to_field='unique_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('artisan', 'job_request'), name='unique_artisan_quote')],
            },
        ),
    ]
