# Generated by Django 5.1.4 on 2025-02-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('quotes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_jobs', to='users.customuser', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.customuser', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='booking',
            name='job_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='jobs.jobrequest', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='artisan',
            field=models.ForeignKey(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='job_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrequest', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='quotes.quoterequest'),
        ),
        migrations.AddConstraint(
            model_name='quoterequest',
            constraint=models.UniqueConstraint(fields=('artisan', 'job_request'), name='unique_artisan_quote'),
        ),
    ]
