# Generated by Django 5.1.4 on 2025-02-22 09:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('quotes', '0001_initial'),
        ('users', '0006_customuser_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_jobs', to='users.customuser', to_field='unique_id')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.customuser', to_field='unique_id')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='jobs.jobrequest', to_field='unique_id')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='quotes.quoterequest')),
            ],
        ),
    ]
